name: 'user-api'
host: 'localhost'
port: 3000
tags: "dev"

user-service:
  name: 'user-service'
  host: 'localhost'
  port: 9000

jwt:
  key: 'tBvO^F6fgurLC#*tMThbdK27RChI@p5d'
  expires: 86400
  issuer: 'starry'

redis:
  host: 'localhost'
  port: '6379'
  password: ''
  db: 1
  expires: 2

email:
  from: 'starry <2413245708@qq.com>'
  subject: 'Register'
  host: "smtp.qq.com"
  port: '587'
  username: '2413245708@qq.com'
  password: ''

consul:
  host: "localhost"
  port: 8500