name: 'user-api'
port: 3000

user-service:
  host: 'localhost'
  port: 9000

jwt:
  key: 'tBvO^F6fgurLC#*tMThbdK27RChI@p5d'
  expires: 86400
  issuer: 'starry'

redis:
  host: 'localhost'
  port: '6379'
  password: ''
  db: 1